spring:
  application:
    name: eureka-server

  config:
    import: configserver:http://localhost:8086/

  profiles:
    active: default


logging:
  level:
    root: info
  pattern:
    console: "%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n"
